In [100]:
# 1.Load the diabetes dataset into a Pandas DataFrame. 
import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

In [101]:
df=pd.read_csv('diabetes.csv')

In [102]:
# 2.Display the first 5 records.
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [103]:
#3.Display the first ten records of the dataset.
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [104]:
# 4.	Display the last five records of the dataset.
df.tail(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [105]:
# 5.	Display the last ten records of the dataset.
df.tail(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [106]:
# 6.	Display the number of rows and columns in the dataset.
df.shape

(768, 9)

In [107]:
# 7.	Display all column names.
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [108]:
# 8.Display the data types of all columns.
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [109]:
# 9.Display complete information about the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [110]:
#10.	Display the number of unique values in each column.
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [111]:
#11.	Display the unique values in the Outcome column.
df["Outcome"].unique()

array([1, 0], dtype=int64)

In [112]:
#12.	Count the number of patients in each Outcome category.
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [113]:
#13.	Identify the target variable.
target_variable = "Outcome"
print("target variable:",target_variable)
print()

target variable: Outcome

In [114]:
#14.	Separate the features and target variable.
x=df.drop('Outcome',axis=1)
y=df["Outcome"]

print("features: ",x)
print("\ntarget variable",y)

features:       Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

target variable 0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [115]:
#15.	Generate a statistical summary of the dataset.
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [116]:
#16.	Find the average value of each numerical column.
df.mean(numeric_only=True)

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [117]:
#17.	Find the median value of each numerical column.
df.median(numeric_only=True)

Pregnancies                   3.0000
Glucose                     117.0000
BloodPressure                72.0000
SkinThickness                23.0000
Insulin                      30.5000
BMI                          32.0000
DiabetesPedigreeFunction      0.3725
Age                          29.0000
Outcome                       0.0000
dtype: float64

In [118]:
#18.Find the minimum value of each column.
print("minimum value:")
df.min()

minimum value:

Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
dtype: float64

In [119]:
#19.	Find the maximum value of each column.
df.max()

Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

In [120]:
#20.	Find the average glucose level of the patients.
avg_Glucose = df["Glucose"].mean()
print("Average Glucose: ",avg_Glucose)

Average Glucose:  120.89453125

In [121]:
#21.	Find the average BMI of the patients.
avg_BMI = df["BMI"].mean()
print("Average BMI: ",avg_BMI)

Average BMI:  31.992578124999977

In [122]:
#22.	Find the average age of the patients.
avg_Age = df["Age"].mean()
print("Average Age: ",avg_Age)

Average Age:  33.240885416666664

In [123]:
#23.	Find the maximum glucose level.
max_glucose = df["Glucose"].max()
print("Maximum Glucose: ",max_glucose)

Maximum Glucose:  199

In [124]:
#24.	Find the minimum glucose level.
min_glucose = df["Glucose"].max()
print("Minimum Glucose: ",min_glucose)

Minimum Glucose:  199

In [125]:
#25.Find the average glucose level for diabetic patients only.
df[df["Outcome"]==1]["Glucose"].mean()

141.25746268656715

In [126]:
#26.Find the average glucose level for non-diabetic patients
df[df["Outcome"]==0]["Glucose"].mean()

109.98

In [127]:
#27.Count the number of diabetic and non-diabetic patients.
outcome_counts = df["Outcome"].value_counts()
print("non-diabetic patients: ", outcome_counts.get(0))
print("diabetic patients: ", outcome_counts.get(1))

non-diabetic patients:  500
diabetic patients:  268

In [128]:
#28.Calculate the percentage of diabetic and non-diabetic patients.
outcome_counts = df["Outcome"].value_counts(normalize=True)*100
print("non-diabetic patients: ", outcome_counts.get(0),"%")
print("diabetic patients: ", outcome_counts.get(1),"%")

non-diabetic patients:  65.10416666666666 %
diabetic patients:  34.89583333333333 %

In [129]:
#29.Check whether the dataset contains null values.
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [130]:
#30.Calculate the total number of null values in the dataset.
df.isnull().sum().sum()

0

In [131]:
#31.Display only the columns that contain null values 
df.columns[df.isnull().any()]

Index([], dtype='object')

In [132]:
#32.Find the percentage of missing values in each column
df.isnull().mean()*100

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

In [133]:
#33.Check whether any null value exist anywhere in the dataset 
print("Any null values?")
print(df.isnull().values.any())

Any null values?
False

In [134]:
#34.Count the number of zero values in each column 
print("Number of zero values in each column:")
print((df == 0).sum())

Number of zero values in each column:
Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [135]:
#35.Find the number of zero glucose valuesvel
print("Number of zero glucose values:")
print((df["Glucose"] == 0).sum())

Number of zero glucose values:
5

In [136]:
#36.identify columns where zero may represent missing or invalid data
zero_col=df.columns[(df==0).any()]
print(zero_col)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'Outcome'],
      dtype='object')

In [137]:
#37.Replace invalid zero values with NaN
df=df.replace(0,np.nan)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,NaN
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,NaN
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1.0

In [138]:
#38.Check the missing values after replacing zeros with NaN
df.isnull().sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [139]:
#39.Calculate the total number of missing values after replacing zeros.
df.isnull().sum().sum()

1263

In [140]:
#40.calculate percentage of missing values after replacing zeros
df.isnull().mean()*100

Pregnancies                 14.453125
Glucose                      0.651042
BloodPressure                4.557292
SkinThickness               29.557292
Insulin                     48.697917
BMI                          1.432292
DiabetesPedigreeFunction     0.000000
Age                          0.000000
Outcome                     65.104167
dtype: float64

In [141]:
#41.Remove all rows containing missing values.
df.dropna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26,1.0
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53,1.0
13,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59,1.0
14,5.0,166.0,72.0,19.0,175.0,25.8,0.587,51,1.0
19,1.0,115.0,70.0,30.0,96.0,34.6,0.529,32,1.0
...,...,...,...,...,...,...,...,...,...
730,3.0,130.0,78.0,23.0,79.0,28.4,0.323,34,1.0
732,2.0,174.0,88.0,37.0,120.0,44.5,0.646,24,1.0
740,11.0,120.0,80.0,37.0,150.0,42.3,0.785,48,1.0
748,3.0,187.0,70.0,22.0,200.0,36.4,0.408,36,1.0
755,1.0,128.0,88.0,39.0,110.0,36.5,1.057,37,1.0

In [142]:
#42.Display the shape of the original dataset.
df.shape

(768, 9)

In [143]:
#43.Display the shape of the dataset after removing missing values.
df_no_missing.shape

(111, 9)

In [144]:
#44.Check whether any missing values remain after removing rows.

In [145]:
#45.Create a copy of the dataset before filling missing values.

In [146]:
#46.Fill missing values using the mean.

In [147]:
#47.Check the information of the cleaned dataset.

In [148]:
#48.Check whether the cleaned dataset contains any missing values.

In [149]:
#49.Display the statistical summary of the cleaned dataset.

In [150]:
#50.Perform the complete data-cleaning process from loading the dataset to filling missing values using the median.